### ISSUE TITLE
is this the paper refenence

### ISSUE THREAD

**Issue by rw1995** [dwright04/Noisy-Labels-with-Bootstrapping#1] opened 2021-01-14 05:15 UTC
Hello, I found that this code is not the content of noisy labels with bootstrapping paper. It's only the the baseline?

**Comment by dr-darryl-wright** [comment] 2021-01-15 04:34
Correct, running train.py will only run the baseline model.  There is also my best attempt to implement the recon loss model here:

https://github.com/dr-darryl-wright/Noisy-Labels-with-Bootstrapping/blob/192fcbc0d9e5a4533cfe00fa4063b2e9204e2fac/train.py#L129

However, I haven't been able to reproduce the results from the paper with this implementation (even for the baseline model).  Some details on the training strategy are missing from the paper.  I tried contacting the authors but didn't get a response.

**Comment by rw1995** [comment] 2021-01-15 06:47
hi， dr_darryl-wright, thanks for your reply.
This is some think as follow:
In the first half of this paper, the author introduces the idea of softmax, mainly to connect softmax with DNN, and then proposes bootstrapping technology. However， In your code, I see that you added two full connection layers at the end. But I can't understand the bootstrapping method very well. Can you tell me something about it?

**Comment by rw1995** [comment] 2021-01-15 07:16
sorry， when I have given the baseline-model, I replace
`noise_grid, accs = evaluate_noise_grid(baseline_model_getter)`   with `noise_grid, accs = evaluate_noise_grid(bootstrap_recon_model_getter)`,
but I get the error, 
`ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0....
`

something is wrong?

**Comment by dr-darryl-wright** [comment] 2021-01-28 02:34
I have updated train.py to run an example of training the bootstrap recon model with a noise fraction of 0.4.

Similar to Fig 2 in the paper this will plot the following :

<img width="562" alt="Screen Shot 2021-01-27 at 20 17 33" src="https://user-images.githubusercontent.com/41346415/106081052-ddca6580-60dd-11eb-95b0-0434959b2819.png">

(left)label noise pattern (right) Learned $W_{(ij)}^{(2)}$


To be clear, I haven't worked on this project in quite some time and it looks like I was in the middle of rewriting.  Since I also haven't been able to replicate the results from the paper the code here should not be trusted as a faithful implementation of the algorithm presented in the paper.

That being said, hopefully, it is a helpful starting point.  If you do manage to replicate the results from the paper I would love to hear what you did.

**Comment by dr-darryl-wright** [comment] 2021-04-01 03:06
Closing this for now.

**Closed as completed** 2021-04-01 03:06 UTC
